#!/bin/bash
module load vcftools/0.1.15
module load vcflib/1.0
module load parallel/20160722

cp ../mapping/raw.6.5.vcf/Final90.5.5.recode.vcf .

grep CHROM Final90.5.5.recode.vcf | cut -f10- | tr '\t' '\n' > popRMI
awk '{print substr($0,1,5)}' popRMI | uniq  > popidHET

#Filter with Freq HET (This is my trick)

#maf
vcftools --vcf Final90.5.5.recode.vcf --maf 0.01 --recode --recode-INFO-all --out af001
After filtering, kept 148 out of 148 Individuals
After filtering, kept 31967 out of a possible 42486 Sites

#counting het
vcftools --vcf af001.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>af001.het
done
paste popidHET af001.het

CA_SR   Average HET 0.636833
CA_ST   Average HET 0.620076
LA_AT   Average HET 0.645081
LA_PS   Average HET 0.803019
VN_DL   Average HET 0.633108


#dp
dp=5
vcftools --vcf af001.recode.vcf --min-meanDP $dp --recode --recode-INFO-all --out dp5
After filtering, kept 148 out of 148 Individuals
After filtering, kept 31868 out of a possible 31967 Sites

#counting het
vcftools --vcf dp5.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>dp5.het
done
paste popidHET dp5.het

CA_SR   Average HET 0.637646
CA_ST   Average HET 0.620796
LA_AT   Average HET 0.645791
LA_PS   Average HET 0.803735
VN_DL   Average HET 0.633607


#######################################################################
#loai bo indel
vcftools --vcf dp5.recode.vcf --remove-indels --recode --recode-INFO-all --out indel
After filtering, kept 148 out of 148 Individuals
After filtering, kept 18407 out of a possible 31868 Sites

#counting het
vcftools --vcf indel.recode.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>indel.het
done
paste popidHET indel.het

CA_SR   Average HET 0.611446
CA_ST   Average HET 0.596898
LA_AT   Average HET 0.622373
LA_PS   Average HET 0.786001
VN_DL   Average HET 0.614872


#saf
vcffilter -f "SAF / SAR > 100 & SRF / SRR > 100 | SAR / SAF > 100 & SRR / SRF > 100" -s indel.recode.vcf > saf.vcf
awk '!/#/' saf.vcf | wc -l
11240

#counting het
vcftools --vcf saf.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>saf.het
done
paste popidHET saf.het

CA_SR   Average HET 0.792049
CA_ST   Average HET 0.790578
LA_AT   Average HET 0.816107
LA_PS   Average HET 0.897874
VN_DL   Average HET 0.824796

#mqm
vcffilter -f "MQM / MQMR > 0.95 & MQM / MQMR < 1.05" saf.vcf > mqm.vcf
grep -v '#' mqm.vcf | wc -l
10159

#counting het
vcftools --vcf mqm.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>mqm.het
done
paste popidHET mqm.het

CA_SR   Average HET 0.814561
CA_ST   Average HET 0.815426
LA_AT   Average HET 0.838575
LA_PS   Average HET 0.922412
VN_DL   Average HET 0.85315


#LOC AB
vcffilter -f "AB >0.25 & AB <0.75 | AB <0.01" mqm.vcf > ab.vcf
grep -v '#' ab.vcf | wc -l
8907

#counting het
vcftools --vcf ab.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>ab.het
done
paste popidHET ab.het

CA_SR   Average HET 0.839403
CA_ST   Average HET 0.840832
LA_AT   Average HET 0.866354
LA_PS   Average HET 0.94028
VN_DL   Average HET 0.881191

#Q40 - Q30
vcftools --vcf indel.recode.vcf --minQ 30 --recode --recode-INFO-all --out Q30
After filtering, kept 148 out of 148 Individuals
After filtering, kept 18407 out of a possible 18407 Sites

#counting het
vcftools --vcf Q30.recode.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>Q30.het
done
paste popidHET Q30.het

CA_SR   Average HET 0.611446
CA_ST   Average HET 0.596898
LA_AT   Average HET 0.622373
LA_PS   Average HET 0.786001
VN_DL   Average HET 0.614872

#prim
vcfallelicprimitives Q30.recode.vcf --keep-info --keep-geno > prim.vcf
vcftools --vcf prim.vcf --remove-indels --recode --recode-INFO-all --out prim.indel
vcftools --vcf prim.indel.recode.vcf --min-alleles 2 --max-alleles 2 --recode --recode-INFO-all --out prim.indel.2
After filtering, kept 148 out of 148 Individuals
After filtering, kept 17643 out of a possible 18407 Sites


#counting het
vcftools --vcf prim.indel.2.recode.vcf  --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>prim.het
done
paste popidHET prim.het

CA_SR   Average HET 0.611446
CA_ST   Average HET 0.596898
LA_AT   Average HET 0.622373
LA_PS   Average HET 0.786001
VN_DL   Average HET 0.614872


######################################################

vcftools --vcf prim.indel.2.recode.vcf --missing-indv

grep -v 'IN' out.imiss | cut -f5 > totalmissing
gnuplot
set terminal dumb size 120, 30
set autoscale 
unset label
set title "Histogram of % missing data per individual"
set ylabel "Number of Occurrences"
set xlabel "% of missing data"
#set yr [0:100000]
binwidth=0.01
bin(x,width)=width*floor(x/width) + binwidth/2.0
plot 'totalmissing' using (bin($1,binwidth)):(1.0) smooth freq with boxes
exit

                                         Histogram of % missing data per individual
  Number of Occurrences
    60 ++---------+----------+----------+----------+----------+----------+----------+----------+----------+---------++
       **         +          +          +          +          + 'totalmissing' using (bin($1,binwidth)):(1.0) ****** +
       **                                                                                                            |
       **                                                                                                            |
    50 **                                                                                                           ++
       **                                                                                                            |
       **                                                                                                            |
       **                                                                                                            |
    40 **                                                                                                           ++
       **                                                                                                            |
       **                                                                                                            |
       **                                                                                                            |
    30 **                                                                                                           ++
       **                                                                                                            |
       ***                                                                                                           |
       ***                                                                                                           |
    20 ***                                                                                                          ++
       ***                                                                                                           |
       *****                                                                                                         |
       *****                                                                                                         |
    10 *******                                                                                                      ++
       ***** *                                                                                                       |
       ***** **                                                                                                      |
       ***** **** ***        +     *******         +          +          +          +          +      **********     +
     0 *********************************************************************************************************----++
       0         0.1        0.2        0.3        0.4        0.5        0.6        0.7        0.8        0.9         1
                                                      % of missing data

awk '$5 > 0.1' out.imiss | cut -f1 > lowDP.indv
nano lowDP.indv

vcftools --vcf prim.indel.2.recode.vcf --remove lowDP.indv --recode --recode-INFO-all --out rmind
After filtering, kept 133 out of 148 Individuals
After filtering, kept 17643 out of a possible 17643 Sites


#make goup ID
grep CHROM rmind.recode.vcf | cut -f10- | tr '\t' '\n' > popRMI
awk '{print substr($0,1,5)}' popRMI | uniq  > popidHET

#counting het
vcftools --vcf rmind.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>rmind.het
done
paste popidHET rmind.het

CA_SR   Average HET 0.583961
CA_ST   Average HET 0.588471
LA_AT   Average HET 0.620085
LA_PS   Average HET 0.788402
VN_DL   Average HET 0.614893


#qual/dp
#QUAL / DP < 0.1 <<< thi het cang co nhieu gia tri <0
#QUAL / DP >0.75 .5 .1 >>> thi HET <<<
vcffilter -f "QUAL / DP > 0.25 | QUAL / DP <0.1" rmind.recode.vcf > fil.vcf
vcftools --vcf fil.vcf --site-quality
cut -f3 out.lqual > qual.depth
grep -v 'D' qual.depth | awk -v x=133 '{print $1/x}' > meanqualsite
#x=individuals numbers

gnuplot
set terminal dumb size 120, 30
set autoscale
set xrange [05:150] 
unset label
set title "Histogram of mean quality per site"
set ylabel "Number of Occurrences"
set xlabel "Mean Quality"
binwidth=1
bin(x,width)=width*floor(x/width) + binwidth/2.0
set xtics 5
plot 'meanqualsite' using (bin($1,binwidth)):(1.0) smooth freq with boxes
exit

                                             Histogram of mean quality per site
  Number of Occurrences
    450 *+--+---+--+---+---+---+--+---+---+---+--+---+---+---+--+---+---+---+--+---+---+---+--+---+---+---+--+---+--++
        *   +   +  +   +   +   +  +   +   +   +  +   +   +   +  'meanqualsite' using (bin($1,binwidth)):(1.0)+****** +
        **                                                                                                           |
    400 **                                                                                                          ++
        **                                                                                                           |
    350 **                                                                                                          ++
        ***                                                                                                          |
        ****                                                                                                         |
    300 ****                                                                                                        ++
        ****                                                                                                         |
        *****                                                                                                        |
    250 ******                                                                                                      ++
        ******                                                                                                       |
    200 ******                                                                                                      ++
        ******                                                                                                       |
        *********                                                                                                    |
    150 *********                                                                                                   ++
        **********                                                                                                   |
        **************                                                                                               |
    100 ******************                                                                                          ++
        ************************ ****                                                                                |
     50 *****************************************  *****  **** **     **          **                                ++
        ******************************************************************* ***************** ***** *** *****   ** **|
        **************************************************************************************************************
      0 **************************************************************************************************************
        5   10  15 20  25  30  35 40  45  50  55 60  65  70  75 80  85  90  95100 105 110 115120 125 130 135140 145 150
                                                        Mean Quality

paste out.lqual meanqualsite | awk -v x=150 '$4>x' | awk '{print $1"\t"$2}' > rmqual.site
#Col1: Contigs
#Col2: Positoion
#meanqualsite >>> thi HET <<<
vcftools --vcf fil.vcf --exclude-positions rmqual.site --recode --recode-INFO-all --out meanqual
After filtering, kept 133 out of 133 Individuals
After filtering, kept 12892 out of a possible 15858 Sites


#counting het
vcftools --vcf meanqual.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>meanqual.het
done
paste popidHET meanqual.het

CA_SR   Average HET 0.552561
CA_ST   Average HET 0.558552
LA_AT   Average HET 0.59213
LA_PS   Average HET 0.753212
VN_DL   Average HET 0.58873


#maxdp
cut -f8  meanqual.recode.vcf | grep -oe "DP=[0-9]*" | sed -s 's/DP=//g' > fil.depth
grep -v '#' fil.vcf | cut -f1,2,6 > fil.loci.qual
awk '{ sum += $1; n++ } END { if (n > 0) print sum / n; }' fil.depth
3038.17
python -c "print int(3038+3*(3038**0.5))"
3203

paste fil.loci.qual fil.depth | awk -v x=3203 '$4 > x' | awk '$3 < 2 * $4' > fil.lowQDloci
vcftools --vcf meanqual.recode.vcf --site-depth --exclude-positions fil.lowQDloci --out fil
cut -f3 fil.ldepth > fil.site.depth
grep -v 'D' fil.site.depth | awk -v x=133 '{print $1/x}' > meandepthpersite
#x=individuals numbers

gnuplot
set terminal dumb size 120, 30
set autoscale
set xrange [05:150] 
unset label
set title "Histogram of mean depth per site"
set ylabel "Number of Occurrences"
set xlabel "Mean Depth"
binwidth=1
bin(x,width)=width*floor(x/width) + binwidth/2.0
set xtics 5
plot 'meandepthpersite' using (bin($1,binwidth)):(1.0) smooth freq with boxes
exit

                                               Histogram of mean depth per site
  Number of Occurrences
    1000 ++--+--+---+---+---+--+---+---+---+--+---+---+--+---+---+---+--+---+---+--+---+---+---+--+---+---+---+--+--++
         +   + ***  +   +   +  +   +   +   +  +   +   +  +  'meandepthpersite' using (bin($1,binwidth)):(1.0) ****** +
     900 ++    ***                                                                                                  ++
         |     ***                                                                                                   |
         |     ***                                                                                                   |
     800 ++    ****                                                                                                 ++
         |   ******                                                                                                  |
     700 ++  *******                                                                                                ++
         |   *******                                                                                                 |
         |  ********                                                                                                 |
     600 ++ ********                                                                                                ++
         |  ********                                                                                                 |
     500 ++ ********                                                                                                ++
         |  ********                                                                                                 |
     400 ++ ********                                                                                                ++
         | ***********                                                                                               |
         | ***********                                                                                               |
     300 ++***********                                                                                              ++
         | ***********                                                                                               |
     200 +*************                                                                                             ++
         |**************                                                                                             |
         |***************                                                                                            |
     100 +*******************                                                                                       ++
         ********************************  +  +   **  +  +   +   +   +  +   +   +  +   +   +   +  +   +   +   +  +   +
       0 *************************************************************************************************************
         5   10 15  20  25  30 35  40  45  50 55  60  65 70  75  80  85 90  95 100105 110 115 120125 130 135 140145 150
                                                          Mean Depth

vcftools --vcf meanqual.recode.vcf --recode --recode-INFO-all --max-meanDP 45 --exclude-positions fil.lowQDloci --out maxDP
#max-meanDP cuc tri ben phai >>> thi HET <<<
After filtering, kept 133 out of 133 Individuals
After filtering, kept 10638 out of a possible 12892 Sites


#counting het
vcftools --vcf maxDP.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>maxDP.het
done
paste popidHET maxDP.het

CA_SR   Average HET 0.583114
CA_ST   Average HET 0.591175
LA_AT   Average HET 0.628481
LA_PS   Average HET 0.795303
VN_DL   Average HET 0.618864

#HET reality
vcffilter -f "PAIRED > 0.05 & PAIREDR > 0.05 & PAIREDR / PAIRED < 1.75 & PAIREDR / PAIRED > 0.05 | PAIRED < 0.05 & PAIREDR < 0.05" -s maxDP.recode.vcf > pair.vcf
grep -v '#' pair.vcf | wc -l
7702

#counting het
vcftools --vcf pair.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>pair.het
done
paste popidHET pair.het

CA_SR   Average HET 0.707708
CA_ST   Average HET 0.724112
LA_AT   Average HET 0.761444
LA_PS   Average HET 0.842287
VN_DL   Average HET 0.773641


#af 0.05
vcftools --vcf pair.vcf --maf 0.05 --recode --recode-INFO-all --out af005
After filtering, kept 133 out of 133 Individuals
After filtering, kept 4902 out of a possible 7702 Sites


#counting het
vcftools --vcf af005.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>af005.het
done
paste popidHET af005.het

CA_SR   Average HET 0.789273
CA_ST   Average HET 0.795511
LA_AT   Average HET 0.797883
LA_PS   Average HET 0.884578
VN_DL   Average HET 0.812482

#hardy-weinberg
vcftools --vcf af005.recode.vcf --hardy
awk -v x=0.000005 '$6<x' out.hwe | awk '{print $1"\t"$2}' | awk '!/POS/' > hardy.site
vcftools --vcf af005.recode.vcf --exclude-positions hardy.site --recode --recode-INFO-all --out hardy
After filtering, kept 133 out of 133 Individuals
After filtering, kept 1141 out of a possible 4902 Sites


#counting het
vcftools --vcf hardy.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>hardy.het
done
paste popidHET hardy.het

CA_SR   Average HET -0.0886303
CA_ST   Average HET -0.00727176
LA_AT   Average HET 0.0311768
LA_PS   Average HET 0.408204
VN_DL   Average HET 0.174275


#max-missing 
vcftools --vcf hardy.recode.vcf --max-missing 0.95 --recode --recode-INFO-all --out geno95
After filtering, kept 133 out of 133 Individuals
After filtering, kept 989 out of a possible 1141 Sites

#counting het
vcftools --vcf geno95.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>geno95.het
done
paste popidHET geno95.het

CA_SR   Average HET -0.0975321
CA_ST   Average HET -0.0172288
LA_AT   Average HET 0.0227632
LA_PS   Average HET 0.43156
VN_DL   Average HET 0.182053


#Graph Individuals with HET >
cut -f5 out.het > loci.het
gnuplot << \EOF
set terminal dumb size 120, 30
set autoscale 
unset label
set title "Frequency of Ho,He per loci"
set ylabel "Number of Occurrences"
set xlabel "% of Ho_He"
#set yr [0:100000]
binwidth=0.01
bin(x,width)=width*floor(x/width) + binwidth/2.0
plot 'loci.het' using (bin($1,binwidth)):(1.0) smooth freq with boxes
pause -1
EOF

                                                Frequency of Ho,He per loci
  Number of Occurrences
    7 ++------------+-------------+-------------**------------+------------+-------------+-------------+------------++
      +             +             +             **            +     'loci.het' using (bin($1,binwidth)):(1.0) ****** +
      |                                         **                                                                   |
      |                                         **                                                                   |
    6 ++                       **               **                                                                  ++
      |                        **               **                                                                   |
      |                        **               **                                                                   |
      |                        **               **                                                                   |
    5 ++                     ****   ***         **     **                                                    ***    ++
      |                      * **   * *         **     **                                                    * *     |
      |                      * **   * *         **     **                                                    * *     |
      |                      * **   * *         **     **                                                    * *     |
    4 ++          ****       * ** *** *   **    **     **   *** ***    ***                                   * *    ++
      |           *  *       * ** * * *   **    **     **   * * * *    * *                                   * *     |
      |           *  *       * ** * * *   **    **     **   * * * *    * *                                   * *     |
      |           *  *       * ** * * *   **    **     **   * * * *    * *                                   * *     |
    3 ++          *  *   ***** **** * **  **    ***    **   * * * *   ** *               ***    *****      *** *    **
      |           *  *   * * * ** * * **  **    ***    **   * * * *   ** *               * *    *   *      * * *    **
      |           *  *   * * * ** * * **  **    ***    **   * * * *   ** *               * *    *   *      * * *    **
      |           *  *   * * * ** * * **  **    ***    **   * * * *   ** *               * *    *   *      * * *    **
    2 ++          *  ***** * * ** * * ****** ** ***  ******** * * *** ** **              * *    *   **** *** * *    **
      |           *  * * * * * ** * * ** *** ** ***  * *** ** * * *** ** **              * *    *   * ** *** * *    **
      |           *  * * * * * ** * * ** *** ** ***  * *** ** * * *** ** **              * *    *   * ** *** * *    **
      +           * +* * * * * ** * * ** *** ** ***  * *** ** * * *** ** **+             * *    *   * ** *** * *    **
    1 ++----------****************************************************************************************************
    -0.3          -0.2          -0.1            0            0.1          0.2           0.3           0.4           0.5
                                                        % of Ho_He

#LOC CIGAR = 1X - chi quan tam den viec thay the tung Allele
#+ missing loci percentage
awk '/#/'  geno95.recode.vcf > cigar.vcf
grep -w "CIGAR=1X" geno95.recode.vcf >> cigar.vcf
awk '!/#/' ciger.vcf | wc -l
989

grep CHROM cigar.vcf | cut -f10- | tr '\t' '\n' > popRMI
awk '{print substr($0,4,2)}' popRMI > popidRMI
paste popRMI popidRMI > popmap.5.5

uniq popidRMI > popid_uniqRMI
t=$(cat popid_uniqRMI)
for i in $t
do
  grep -w $i popmap.5.5 > $i.keep
done

ls *keep | sed 's/.keep//g' | parallel 'vcftools --vcf cigar.vcf --keep {}.keep --missing-site --out {}'
rm  all.badlociRMI
cat *.lmiss | awk '!/CHR/' >> all.badlociRMI

cut -f6 all.badlociRMI > missing.lociRMI
gnuplot << \EOF
set terminal dumb size 120, 30
set autoscale 
unset label
set title "Histogram of % missing data per loci"
set ylabel "Number of Occurrences"
set xlabel "% of missing data"
#set yr [0:100000]
binwidth=0.01
bin(x,width)=width*floor(x/width) + binwidth/2.0
plot 'missing.lociRMI' using (bin($1,binwidth)):(1.0) smooth freq with boxes
pause -1
EOF

                                             Histogram of % missing data per loci
  Number of Occurrences
    4000 ++----------------+-----------------+-----------------+-----------------+-----------------+----------------++
         +                 +                 +               'missing.lociRMI' using (bin($1,binwidth)):(1.0) ****** +
         ******                                                                                                      |
    3500 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
    3000 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
    2500 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
    2000 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
    1500 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
    1000 *+   *                                                                                                     ++
         *    *                                                                                                      |
         *    *                                                                                                      |
     500 *+   *                                                                                                     ++
         *    *     ****                                                                                             |
         *    *******  *********  *****      +                 +                 +                 +                 +
       0 **************************************************************************************************---------++
         0                0.05              0.1               0.15              0.2               0.25              0.3
                                                       % of missing data

awk '$6 > 0.1' all.badlociRMI | cut -f1,2 > bad.lociRMI
vcftools --vcf cigar.vcf --exclude-positions bad.lociRMI --recode --recode-INFO-all --out badlocirm
After filtering, kept 133 out of 133 Individuals
After filtering, kept 712 out of a possible 989 Sites


#counting het
vcftools --vcf badlocirm.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>badlocirm.het
done
paste popidHET badlocirm.het

CA_SR   Average HET -0.118172
CA_ST   Average HET -0.0254056
LA_AT   Average HET -0.0374432
LA_PS   Average HET 0.448024
VN_DL   Average HET 0.196053


#Convert to genepop and calcutate HET by Genalex
#Copy all lines with missing warning in this
nano missingloci.het

uniq missingloci.het
#161 loci in this

#filter low het loci
t=$(cat missingloci.het)
awk '!/#/' badlocirm.recode.vcf > noheader.vcf
awk '/#/' badlocirm.recode.vcf > lowhwe.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> lowhwe.vcf; done

awk '!/#/' lowhwe.vcf | cut -f1,2 > lowhwe.loci
vcftools --vcf badlocirm.recode.vcf --exclude-positions lowhwe.loci --recode --recode-INFO-all --out HighHWE
After filtering, kept 133 out of 133 Individuals
After filtering, kept 551 out of a possible 712 Sites

#ket qua la HIGHHet con thap hon ban dau
#Filter nhung loci danh dau missing chi cua PS xem sao

nano PSmissingloci.het
#40 loci
t=$(cat PSmissingloci.het)
awk '!/#/' badlocirm.recode.vcf > noheader.vcf
awk '/#/' badlocirm.recode.vcf > lowhwe.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> lowhwe.vcf; done

awk '!/#/' lowhwe.vcf | cut -f1,2 > lowhwe.loci
vcftools --vcf badlocirm.recode.vcf --exclude-positions lowhwe.loci --recode --recode-INFO-all --out HighPSHWE
After filtering, kept 133 out of 133 Individuals
After filtering, kept 672 out of a possible 712 Sites


#HWE cutoff
vcftools --vcf vcftools --vcf badlocirm.recode.vcf --hwe 0.01 --recode --recode-INFO-all --out hwecutoff
After filtering, kept 133 out of 133 Individuals
After filtering, kept 499 out of a possible 712 Sites

vcftools --vcf vcftools --vcf HighPSHWE.recode.vcf --hwe 0.01 --recode --recode-INFO-all --out hwecutoffHighPS
After filtering, kept 133 out of 133 Individuals
After filtering, kept 473 out of a possible 672 Sites

vcftools --vcf vcftools --vcf HighHWE.recode.vcf --hwe 0.01 --recode --recode-INFO-all --out hwecutoffHighAll
After filtering, kept 133 out of 133 Individuals
After filtering, kept 393 out of a possible 551 Sites




###########################################################THEM VAI PHAN TICH NUA ROI RUT RA KET LUAN

#Graph Individuals with HET >
cut -f5 out.het > loci.het
gnuplot << \EOF
set terminal dumb size 120, 30
set autoscale 
unset label
set title "Frequency of Ho,He per loci"
set ylabel "Number of Occurrences"
set xlabel "% of Ho_He"
#set yr [0:100000]
binwidth=0.01
bin(x,width)=width*floor(x/width) + binwidth/2.0
plot 'loci.het' using (bin($1,binwidth)):(1.0) smooth freq with boxes
pause -1
EOF

                                                Frequency of Ho,He per loci
  Number of Occurrences
    6 ++---------+----------+----------+----------+-----------+----------+----------+---**-----+----------+---------++
      +          +          +          +          +           +     'loci.het' using (bin($1,binwidth)):(1.0) ****** +
      |                                                                                 **                           |
      |                                                                                 **                           |
      |                                                                                 **                           |
    5 ++                                                                             ** **                          ++
      |                                                                              ** **                           |
      |                                                                              ** **                           |
      |                                                                              ** **                           |
      |                                                                              ** **                           |
    4 ++                                       **      **                        ****** **                          ++
      |                                        **      **                        * **** **                           |
      |                                        **      **                        * **** **                           |
      |                                        **      **                        * **** **                           |
    3 ++                **            ******   ******  ****                      * *******     **                   ++
      |                 **            *** **   **** *  ****                      * *******     **                    |
      |                 **            *** **   **** *  ****                      * *******     **                    |
      |                 **            *** **   **** *  ****                      * *******     **                    |
      |                 **            *** **   **** *  ****                      * *******     **                    |
    2 ++     *****  *** ****   **** ***** ********* *  *****  *********          * ******** ******* **  **  ****    ++
      |      *   *  * * ** *   * ** ***** **** **** *  *****  * * *****          * ******** * *** * **  **  *  *     |
      |      *   *  * * ** *   * ** ***** **** **** *  *****  * * *****          * ******** * *** * **  **  *  *     |
      |      *   *  * * ** *   * ** ***** **** **** *  *****  * * *****          * ******** * *** * **  **  *  *     |
      +      *   *  * * ** *+  * ** ***** **** **** *  *****  * * *****  +       * ******** * *** * **  **+ *  *     +
    1 ++-*******************************************************************************************************----++
    -0.5       -0.4       -0.3       -0.2       -0.1          0         0.1        0.2        0.3        0.4        0.5
                                                        % of Ho_He


#Remove HET >x
awk -v x=0.3 '$5>x' out.het | cut -f1 >het.indv

INDV
LA_PS04
LA_PS07
LA_PS11
LA_PS12
LA_PS16
LA_PS24
LA_PS25
VN_DL04
VN_DL05
VN_DL07
VN_DL11
VN_DL12
VN_DL22
VN_DL23
VN_DL24
VN_DL29

vcftools --vcf hwecutoff.recode.vcf --remove het.indv --recode --recode-INFO-all --out rmindhet
After filtering, kept 117 out of 133 Individuals
After filtering, kept 499 out of a possible 499 Sites

#CREATE POPID 
grep CHROM rmindhet.recode.vcf | cut -f10- | tr '\t' '\n' > popRMI
awk '{print substr($0,4,2)}' popRMI > popidRMI
paste popRMI popidRMI > popmapfinal.5.5

#counting het
vcftools --vcf rmindhet.recode.vcf --het
t=$(cat popidHET)
for i in $t 
do
  grep $i out.het | awk '{SUM+=$5} END {print "Average HET", SUM/NR}' >>rmindhet.het
done
paste popidHET rmindhet.het

CA_SR   Average HET -0.207169
CA_ST   Average HET -0.0832206
LA_AT   Average HET 0.00839421
LA_PS   Average HET 0.261502
VN_DL   Average HET 0.212555

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#SO SANH VS 2 KET QUA O TREN CO THE KET LUAN DUOC VIEC REMOVE INDV KHONG CO Y NGHIA.
#BANG CHUNG O @ FILES: 499final.xlsx va 499hwecutoffonly
#SAU NHIEU PHEP SO SANH NHAN THAY LA:
hwecutoff = 499 loci final (sau khi loai bo cac Individuals co Het >0.3)
Pop	Ho	He
SR	0.222	0.196
ST	0.199	0.185
AT	0.182	0.143
PS	0.135	0.085
DL	0.144	0.120

hwecutoff = 499hwecutoffonly (Khong loai bo cac individulas)
Pop	Ho	He
SR	0.222	0.196
ST	0.199	0.185
AT	0.182	0.143
PS	0.130	0.085
DL	0.133	0.117

badlocirm.recode.vcf (khong filter bang het 0.1)
Pop	Ho	He
SR	0.216	0.191
ST	0.198	0.184
AT	0.200	0.168
PS	0.106	0.073
DL	0.154	0.146

hwe = HighHWE (su dung 712 loci sau cua badlocirm.recode.vcf), sau do remove tat ca missing loci duoc liet ke o sheet HFP
Pop	Ho	He
SR	0.213	0.187
ST	0.198	0.183
AT	0.190	0.160
PS	0.114	0.079
DL	0.166	0.152

hwecutoffHighPS (su dung 712 loci sau cua badlocirm.recode.vcf), sau do remove tat ca missing loci cua PakSe duoc liet ke o sheet HFP
Pop	Ho	He
SR	0.212	0.188
ST	0.195	0.183
AT	0.192	0.163
PS	0.111	0.076
DL	0.157	0.149

hwecutoffHighAll (su dung HighHWE sau do filter het=0.1 nhung so loci 393 thi hoi bi it nen co the kho chap nhan duoc)
Pop	Ho	He
SR	0.218	0.193
ST	0.198	0.183
AT	0.171	0.134
PS	0.138	0.090
DL	0.142	0.123

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#KET LUAN#
#Fileter den HWE cutoff: vcftools --vcf vcftools --vcf badlocirm.recode.vcf --hwe 0.01 --recode --recode-INFO-all --out hwecutoff
#After filtering, kept 133 out of 133 Individuals
#After filtering, kept 499 out of a possible 712 Sites
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


#Filter relatedness individuals first
#Tien hanh test related sau do remove cac ca the nay di
Co qua nhieu cap trong nhom PS nen tam thoi khong su dung relatedness cho nhom nay


#FILTER to choose NEUTRAL AND DIVERGENT testing 
# 76 loci = Divegen 
# 16 loci = Divergen outlier
# 60 loci without outlier
nano divergent.nooutlier

t=$(cat divergent.nooutlier)
awk '!/#/' hwecutoff.recode.vcf > noheader.vcf
awk '/#/' hwecutoff.recode.vcf > divergen_only.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> divergen_only.vcf; done

#394 loci neutral only
nano neutral.loci
t=$(cat neutral.loci)
awk '!/#/' hwecutoff.recode.vcf > noheader.vcf
awk '/#/' hwecutoff.recode.vcf > neutral_only.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> neutral_only.vcf; done

#31 oulier loci for both divergent and balance
nano outlier.loci
t=$(cat outlier.loci)
awk '!/#/' hwecutoff.recode.vcf > noheader.vcf
awk '/#/' hwecutoff.recode.vcf > outlier_only.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> outlier_only.vcf; done

#468 loci removed outlier loci only
nano remove.outlier
t=$(cat remove.outlier)
awk '!/#/' hwecutoff.recode.vcf > noheader.vcf
awk '/#/' hwecutoff.recode.vcf > removed_outlier.vcf
for i in $t; do head -$i noheader.vcf | tail -1 >> removed_outlier.vcf; done

#Filter for migration only
#max-missing 100
vcftools --vcf hwe.recode.vcf --max-missing 1 --recode --recode-INFO-all --out max100


vcftools --vcf hwe.rmsite.recode.vcf --remove related.list --recode --recode-INFO-all --out rmind.related
After filtering, kept 127 out of 134 Individuals
After filtering, kept 541 out of a possible 541 Sites

grep CHROM NeutralLoci.recode.vcf | cut -f10- | tr '\t' '\n' > popRMI
awk '{print substr($0,4,2)}' popRMI > popidRMI
paste popRMI popidRMI > popmap.5.5.related



#Filter for migration bat dau tu cho nay

#Can bang so luong ca the cho tung quan the. Tim quan the co so luong ca the thap nhat(PS=17).
#Loai bo cac ca the trong cac quan the khac sao cho so luong bang nhau (=17)
nano migraterm.indv
INDV
CA_SR02 
CA_SR14 
CA_SR27 
CA_SR01 
CA_SR12 
CA_SR05 
CA_SR19 
CA_SR04 
CA_SR13 
CA_SR22 
CA_SR30 
CA_SR07 
CA_ST02 
CA_ST13 
CA_ST14 
CA_ST17 
CA_ST01 
CA_ST12 
CA_ST05 
CA_ST04 
CA_ST07 
CA_ST16 
CA_ST22 
CA_ST09 
CA_ST06 
CA_ST11 
CA_ST19 
CA_ST39 
CA_ST21 
LA_AT22 
LA_AT21 
VN_DL10 
VN_DL05 
VN_DL26 
VN_DL22 
VN_DL25 
VN_DL27 
VN_DL29 
VN_DL28 
VN_DL23 
VN_DL19 
VN_DL02 

vcftools --vcf NeutralLoci.recode.vcf --remove migraterm.indv --recode --recode-INFO-all --out rmind.4migrate
After filtering, kept 85 out of 127 Individuals
After filtering, kept 535 out of a possible 535 Sites


vcftools --vcf rmind.4migrate.recode.vcf --max-missing 1 --recode --recode-INFO-all --out max100
After filtering, kept 85 out of 85 Individuals
After filtering, kept 348 out of a possible 535 Sites

ln ../../scripts/Filter_one_random_snp_per_contig.sh
./Filter_one_random_snp_per_contig.sh max100.recode.vcf
awk '!/#/' best.max100.vcf | wc -l
205

t=$(pwd)
cd ../mapping
#CutoffCode="6.5"
cp ../../scripts/rad_haplotyper115HPC.pl ./
perl rad_haplotyper115HPC.pl -v $t/best.max100.vcf  -x 32 -mp 1 -u 10 -ml 4 -n -e -p $t/popmap.5.5.related -r reference.5.5.fasta -a $t/migrate.ima
Filtered 0 loci below missing data cutoff
Filtered 0 possible paralogs
Filtered 0 loci with low coverage or genotyping errors
Filtered 0 loci with an excess of haplotypes
Writing IMa file: /work/vietnam/dthinh/2018_3S_O_TB/filter.5.5_Final/migrate.ima


